// -*- mode: idl; indent-tabs-mode: t; tab-width: 4; c-basic-offset: 4; -*-


module OpenHRP
{
  typedef double darray3[3];
  typedef long   iarray4[4];
  typedef sequence<darray3> darray3Seq;
  typedef sequence<iarray4> iarray4Seq;

  interface CvProcessorService
  {
    unsigned long HoughCircles(out darray3Seq circles);
    unsigned long HoughLinesP(out iarray4Seq lines);
  };
};
